### ISSUE TITLE
Falha ao ativar extensão

### ISSUE THREAD

**Issue by netomarchiori** [bernardo-bruning/ollama-copilot#7]
Segui o passo a passo e instalei o ollama-copilot sem problemas, instalei a extensão no VS Code e já estava com o sign in no github feito.

Mesmo ao configurar o `debug.overrideProxyUrl` nos settings, ainda vejo:

`[error] [auth] Extension activation failed: "No access to GitHub Copilot found. You are currently logged in as neto-marchiori."`

e a extensão fica com falha de ativação. tem algum jeito de contornar isso?

**Comment by bernardo-bruning** [comment]
Olá @netomarchiori 

Percebi que realmente o proxy não está funcionando no vscode para usuários que não possuem copilot ativo. 
Consegue testar os seguintes passos?

1. Adicionar nas [configurações](https://code.visualstudio.com/docs/getstarted/settings) um bypass de validação de certificados.
```
https://code.visualstudio.com/docs/getstarted/settings
```

2. Ao executar o vscode forçar proxy no nível de sistema operacional.
```
export HTTPS_PROXY=https://localhost:11435
vscode
```

Esse problema ocorre pois não parece que o VS code está respeitando completamente as configurações de proxy impostas. Vou trabalhar nisso nos próximos dias.

**Comment by netomarchiori** [comment]
testo e te retorno sem falta

**Comment by netomarchiori** [comment]
@bernardo-bruning , nada feito...se forço no nivel do sistema operacional ate parece que deu certo porem vejo um monte de 

`failed to read request: malformed HTTP request`

e

`failed to transfer: writeto tcp [::1]:56449->[::1]:11436`

**Comment by bernardo-bruning** [comment]
@netomarchiori acredito que te induzi a um erro.
Nas configurações de proxy era para ter a URL em http.
```
export HTTPS_PROXY=http://localhost:11435
```

**Comment by netomarchiori** [comment]
nada feito, várias mensagens de `failed to transfer` e `TLS handshake error``

```
2024/05/20 08:58:57 failed to transfer: writeto tcp [::1]:58911->[::1]:11436: readfrom tcp 127.0.0.1:11435->127.0.0.1:58910: read tcp [::1]:58911->[::1]:11436: use of closed network connection
2024/05/20 08:58:57 http: TLS handshake error from [::1]:58911: EOF
````
nas configurações tenho o seguinte

```
"github.copilot.advanced": {
    "debug.overrideProxyUrl": "http://localhost:11437",
  },
  "http.proxy": "http://localhost:11435",
  "http.proxyStrictSSL": false,
```

**Comment by ranzou06** [comment]
tive o mesmo cenário aqui, com os erros de handshake, alguma ideia de como resolver?

**Comment by bernardo-bruning** [comment]
@ranzou06 pode compartilhar logs do vscode e do ollama-copilot?

Consegue testar a ultima versão da master?

**Comment by ritamariavermelho06** [comment]
Quando tiver um tempinho livre coloco para rodar novamente e posto aqui! depois de algumas tentativas passou a funcionar mas, ficou bem instável, algumas requisições davam o erro de certificado, handshake aparecia o tempo inteiro.

**Comment by artromone** [comment]
Could you guys please speak English, it is not comfortable to translate each sentence :)

**Comment by netomarchiori** [comment]
> Could you guys please speak English, it is not comfortable to translate each sentence :)

absolutely! are you also experiencing issues on enabling the extension?

**Comment by artromone** [comment]
> absolutely! are you also experiencing issues on enabling the extension?

good one! :) but I am using vim-like browser with no extensions, and sometimes view the feed using mobile

**Comment by shahrokh-bahtooei** [comment]
I also installed `ollama-copilot` as instructed, set the proxy setting in vscode, and tried separately both `% export HTTPS_PROXY=https://localhost:11435` and `% export HTTPS_PROXY=http://localhost:11435`, but I faced with this error in vscode:
```
2024-08-02 14:48:25.528 [error] [auth] auth: FetchError: self signed certificate
    at fetch (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at XO.fetch (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/lib/src/network/helix.ts:96:22)
    at fetchCopilotToken (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/lib/src/auth/copilotToken.ts:197:16)
    at authFromGitHubToken (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/lib/src/auth/copilotToken.ts:130:22)
    at auth (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/extension/src/auth.ts:40:25)
    at authShowWarnings (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/extension/src/auth.ts:131:25)
    at EM.getCopilotToken (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/extension/src/auth.ts:174:33)
    at attemptAuthentication (/Users/Sh/.vscode/extensions/github.copilot-1.219.0/extension/src/auth.ts:58:9) {
  type: 'system',
  _name: 'FetchError',
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
  errno: undefined,
  erroredSysCall: undefined
}
2024-08-02 14:48:25.529 [error] [auth] self signed certificate
```

The `Chat` sidebar still shows that I need to sign in:
<img width="389" alt="Screen Shot 1403-05-12 at 14 58 41" src="https://github.com/user-attachments/assets/e3b5df68-2f4e-469a-b800-5c656489239a">

I cannot use GitHub Copilot actions in Command Palette:
<img width="263" alt="Screen Shot 1403-05-12 at 15 00 18" src="https://github.com/user-attachments/assets/2982b574-9df4-4cfc-ba66-30d617ce43d3">

Ollama is running and local models work correctly in other interfaces, e.g. LLM-X. Still, wondering about a good extension/plugin in VSCode or preferably PyCharm to work fluently with local LLMs . . .   If only we could use GitHub Copilot as a well-designed extension but with our local LLMs . . .
